'use client';

import { useState, useEffect } from 'react';
import BarChart from '@/components/charts/bar-chart';

interface ReportData {
  period: {
    range: string;
    startDate: string;
    endDate: string;
  };
  summary: {
    totalEvents: number;
    tasksCompleted: number;
    activeProjects: number;
    generatedAt: string;
  };
  timeline: Array<{ date: string; events: number }>;
  tasks: {
    completed: number;
    pending: number;
    failed: number;
  };
  agents: Array<{ agent: string; events: number }>;
  projects: Array<{ name: string; phase: string; status: string }>;
}

export default function ReportsClient() {
  const [reportData, setReportData] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(false);
  const [dateRange, setDateRange] = useState('week');
  const [customFrom, setCustomFrom] = useState('');
  const [customTo, setCustomTo] = useState('');

  const fetchReport = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ range: dateRange });
      if (dateRange === 'custom' && customFrom && customTo) {
        params.append('from', customFrom);
        params.append('to', customTo);
      }

      const response = await fetch(`/api/reports?${params}`);
      if (response.ok) {
        const data = await response.json();
        setReportData(data);
      }
    } catch (error) {
      console.error('Error fetching report:', error);
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchReport();
  }, [dateRange, customFrom, customTo]);

  const generateMarkdownReport = () => {
    if (!reportData) return;

    const markdown = `# Activity Report

**Period:** ${reportData.period.startDate} to ${reportData.period.endDate}
**Generated:** ${new Date(reportData.summary.generatedAt).toLocaleString()}

## Executive Summary

- **Total Events:** ${reportData.summary.totalEvents}
- **Tasks Completed:** ${reportData.summary.tasksCompleted}
- **Active Projects:** ${reportData.summary.activeProjects}

## Task Completion

- ✅ **Completed:** ${reportData.tasks.completed}
- ⏳ **Pending:** ${reportData.tasks.pending}
- ❌ **Failed:** ${reportData.tasks.failed}

## Agent Activity

${reportData.agents.map(agent => `- **${agent.agent}:** ${agent.events} events`).join('\n')}

## Project Status

${reportData.projects.map(project => `- **${project.name}** - ${project.phase} (${project.status})`).join('\n')}

## Activity Timeline

${reportData.timeline.map(day => `- **${day.date}:** ${day.events} events`).join('\n')}

---
*Generated by Grid Dashboard Analytics*
`;

    navigator.clipboard.writeText(markdown);
    alert('Report copied to clipboard as Markdown!');
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return <div className="text-[--grid-text-dim]">Generating report...</div>;
  }

  if (!reportData) {
    return <div className="text-[--grid-text-dim]">Failed to load report data</div>;
  }

  return (
    <div className="space-y-8">
      {/* Controls */}
      <div className="bg-[--grid-surface] border border-[--grid-border] rounded-lg p-6">
        <h2 className="text-xl font-bold text-[--grid-text] mb-4">Report Configuration</h2>
        
        <div className="flex flex-wrap gap-4 items-end">
          <div>
            <label className="block text-sm font-semibold text-[--grid-text-dim] mb-2">
              Date Range
            </label>
            <select
              value={dateRange}
              onChange={(e) => setDateRange(e.target.value)}
              className="px-3 py-2 border border-[--grid-border] rounded bg-[--grid-bg] text-[--grid-text] font-mono"
            >
              <option value="week">This Week</option>
              <option value="month">This Month</option>
              <option value="custom">Custom Range</option>
            </select>
          </div>

          {dateRange === 'custom' && (
            <>
              <div>
                <label className="block text-sm font-semibold text-[--grid-text-dim] mb-2">
                  From
                </label>
                <input
                  type="date"
                  value={customFrom}
                  onChange={(e) => setCustomFrom(e.target.value)}
                  className="px-3 py-2 border border-[--grid-border] rounded bg-[--grid-bg] text-[--grid-text] font-mono"
                />
              </div>
              
              <div>
                <label className="block text-sm font-semibold text-[--grid-text-dim] mb-2">
                  To
                </label>
                <input
                  type="date"
                  value={customTo}
                  onChange={(e) => setCustomTo(e.target.value)}
                  className="px-3 py-2 border border-[--grid-border] rounded bg-[--grid-bg] text-[--grid-text] font-mono"
                />
              </div>
            </>
          )}

          <div className="flex gap-2">
            <button
              onClick={generateMarkdownReport}
              className="px-4 py-2 bg-[--grid-accent] text-white rounded hover:opacity-80 font-mono"
            >
              📋 Copy as Markdown
            </button>
            <button
              onClick={handlePrint}
              className="px-4 py-2 border border-[--grid-border] text-[--grid-text] rounded hover:bg-[--grid-surface] font-mono"
            >
              🖨️ Print
            </button>
          </div>
        </div>
      </div>

      {/* Executive Summary */}
      <div className="bg-[--grid-surface] border border-[--grid-border] rounded-lg p-6">
        <h2 className="text-xl font-bold text-[--grid-text] mb-4">Executive Summary</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="text-center">
            <div className="text-3xl font-bold text-[--grid-accent] font-mono">
              {reportData.summary.totalEvents}
            </div>
            <div className="text-[--grid-text-dim]">Total Events</div>
          </div>
          <div className="text-center">
            <div className="text-3xl font-bold text-[--grid-accent] font-mono">
              {reportData.summary.tasksCompleted}
            </div>
            <div className="text-[--grid-text-dim]">Tasks Completed</div>
          </div>
          <div className="text-center">
            <div className="text-3xl font-bold text-[--grid-accent] font-mono">
              {reportData.summary.activeProjects}
            </div>
            <div className="text-[--grid-text-dim]">Active Projects</div>
          </div>
        </div>
        <div className="mt-4 text-sm text-[--grid-text-dim] text-center">
          Report period: {reportData.period.startDate} to {reportData.period.endDate}
        </div>
      </div>

      {/* Activity Timeline */}
      <div className="bg-[--grid-surface] border border-[--grid-border] rounded-lg p-6">
        <h2 className="text-xl font-bold text-[--grid-text] mb-4">Activity Timeline</h2>
        <div className="flex justify-center">
          <BarChart
            data={reportData.timeline.map(item => ({
              label: new Date(item.date).toLocaleDateString('en', { weekday: 'short', day: 'numeric' }),
              value: item.events
            }))}
            width={600}
            height={250}
            color="var(--grid-accent)"
          />
        </div>
      </div>

      {/* Task Completion & Agent Activity */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Task Completion */}
        <div className="bg-[--grid-surface] border border-[--grid-border] rounded-lg p-6">
          <h2 className="text-xl font-bold text-[--grid-text] mb-4">Task Completion</h2>
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="flex items-center gap-2">
                <span className="w-3 h-3 bg-green-500 rounded-full"></span>
                Completed
              </span>
              <span className="font-mono font-bold">{reportData.tasks.completed}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="flex items-center gap-2">
                <span className="w-3 h-3 bg-yellow-500 rounded-full"></span>
                Pending
              </span>
              <span className="font-mono font-bold">{reportData.tasks.pending}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="flex items-center gap-2">
                <span className="w-3 h-3 bg-red-500 rounded-full"></span>
                Failed
              </span>
              <span className="font-mono font-bold">{reportData.tasks.failed}</span>
            </div>
          </div>
          
          {/* Simple progress bar */}
          <div className="mt-4">
            <div className="h-3 bg-[--grid-bg] rounded-full overflow-hidden">
              {(() => {
                const total = reportData.tasks.completed + reportData.tasks.pending + reportData.tasks.failed;
                const completedPercent = (reportData.tasks.completed / total) * 100;
                const pendingPercent = (reportData.tasks.pending / total) * 100;
                
                return (
                  <>
                    <div 
                      className="h-full bg-green-500 float-left"
                      style={{ width: `${completedPercent}%` }}
                    />
                    <div 
                      className="h-full bg-yellow-500 float-left"
                      style={{ width: `${pendingPercent}%` }}
                    />
                    <div 
                      className="h-full bg-red-500 float-left"
                      style={{ width: `${100 - completedPercent - pendingPercent}%` }}
                    />
                  </>
                );
              })()}
            </div>
          </div>
        </div>

        {/* Agent Activity */}
        <div className="bg-[--grid-surface] border border-[--grid-border] rounded-lg p-6">
          <h2 className="text-xl font-bold text-[--grid-text] mb-4">Agent Activity</h2>
          <div className="space-y-3">
            {reportData.agents.map((agent, index) => (
              <div key={index} className="flex items-center justify-between">
                <span className="font-mono font-bold">{agent.agent}</span>
                <div className="flex items-center gap-2">
                  <div className="w-24 h-2 bg-[--grid-bg] rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-[--grid-accent] rounded-full"
                      style={{ 
                        width: `${(agent.events / Math.max(...reportData.agents.map(a => a.events))) * 100}%` 
                      }}
                    />
                  </div>
                  <span className="font-mono text-sm w-8 text-right">{agent.events}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Project Status */}
      <div className="bg-[--grid-surface] border border-[--grid-border] rounded-lg p-6">
        <h2 className="text-xl font-bold text-[--grid-text] mb-4">Project Status</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {reportData.projects.map((project, index) => (
            <div key={index} className="border border-[--grid-border] rounded p-4">
              <h3 className="font-semibold text-[--grid-text] mb-2">{project.name}</h3>
              <div className="space-y-1">
                <div className="flex justify-between text-sm">
                  <span className="text-[--grid-text-dim]">Phase:</span>
                  <span className="font-mono capitalize">{project.phase}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-[--grid-text-dim]">Status:</span>
                  <span className={`font-mono capitalize ${
                    project.status === 'active' ? 'text-green-500' :
                    project.status === 'completed' ? 'text-blue-500' : 'text-gray-500'
                  }`}>
                    {project.status}
                  </span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          body * {
            visibility: hidden;
          }
          
          .print-section, .print-section * {
            visibility: visible;
          }
          
          .print-section {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
          }
          
          button {
            display: none !important;
          }
          
          .no-print {
            display: none !important;
          }
        }
      `}</style>
    </div>
  );
}